bacpop-138 Validate project name change
bacpop/beebop pull request #40
Opened 2023-08-02 10:28 UTC by EmmaLRussell

This branch adds some validation when user edits project name - project name will not be changed if name is empty or whitespace, or if another of the user's projects has the same name. 

Key changes:
- added a getter to do the actual check, as we'll also want to use this for creating new projects (that validation tbd in a separate branch), and an enum for the possible check results. 
- updated `EditProjectName` component to check candidate project name on each key change, prevent saving when validation fails and show an appropriate message. To avoid user alarm, there is no error message or button disable if the name is identical to the current name, but nothing will happen if click 'Save' at this point. 
- Removed 'Project' prefix from Project page header - I don't think it was useful, and it was causing formatting headaches when editing!

2023-08-04 11:30 UTC, M-Kusumgar requested changes
Looks good, however I think we should only allow one edit at a time, maybe turn off edit mode on blur, because if you do the steps below, you can name two projects the same thing
1. Create two projects with whatever names
2. Toggle both to edit mode on the projects home page
3. Change them to the same name and save

2023-08-08 10:03 UTC, EmmaLRussell commented
> Looks good, however I think we should only allow one edit at a time, maybe turn off edit mode on blur, because if you do the steps below, you can name two projects the same thing
> 
>     1. Create two projects with whatever names
> 
>     2. Toggle both to edit mode on the projects home page
> 
>     3. Change them to the same name and save

Ha, yep, good point!

2023-08-08 13:59 UTC, EmmaLRussell commented
Made a few little changes to support only allowing one project name at a time to be edited:
- cancel the edit when the component loses focus - added an enclosing div to catch this event
- make sure that the component actually has focus when editing starts! Focus the input when edit button is first pressed - do this on nextTick to ensure the input is available.
- Set a fixed height on the component which is the same whether in editing or non-editing mode - this prevents UI jumping around and also avoids problem of click event on the icon getting lost because the focus out on an above component jumped up the UI so the click location was no longer over the icon.

2023-08-10 13:33 UTC, M-Kusumgar approved these changes
Just tested it out! Looks good and the code looks good! The way I did it in wodin is just by having it go to non-edit mode on blur and the handleBlur function also checks if event.relatedTarget was the button or not, so that is one way you can customise blur events so that they will let through events from certain other objects in the UI! But mousedown works too!

2023-08-10 15:05 UTC, merged